### ISSUE TITLE
Bitcoin shows as confirmed in 0.1.1 but unconfirmed in 0.5.1

### ISSUE THREAD

**Issue by xauxatz** [Multibit-Legacy/multibit-hd#980] opened 2017-04-21 05:38 UTC
I've had a number of bitcoins in Multibit HD for several years with no problems and no trades.
Yesterday, when I opened 0.5.1, it suddenly showed as unconfirmed (with 10 peers).
I tried to repair the wallet many times, and restore from wallet words also several times, without success.

Following advice from others here, I tried to install earlier versions but had to go all the way back to 0.1.1 to get my bitcoins confirmed. However, I still cannot get it to work in 0.5.1.

What can I do?

**Comment by Wahwahboy** [comment] 2017-05-01 23:07
Same here 0.5.1 multibit HD unconfirmed. It  means I cannot perform any transactions and I cannot empty wallet due to insufficient funds.
I've only ever made 2 transactions on this wallet - I transferred from multibit classic over a year ago.
I'm stuck.

**Comment by xauxatz** [comment] 2017-05-02 06:17
Hi - I solved my problem by continuing to repair wallet and create from 
wallet words in 0.1.1 - and then trying again in 0.5.1.
Eventually after a number of repetitions, the wallet also confirmed in 
0.5.1.

**Comment by Wahwahboy** [comment] 2017-05-02 23:10
Thanks for the comment - after repairing several times over several days, it worked...strange.
Hurrah!
I didn't need to downgrade but I did run repair around 6 times at least I think.

**Closed as completed** 2017-05-18 05:41 UTC

**Comment by doge2021** [comment] 2024-11-27 13:35
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
